### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [rixwew/darts-clone-python#10]
Problem
---------
On aarch64, `pip install dartsclone` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install dartsclone` should download the wheels from PyPI.

@rixwew, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by rixwew** [comment]
Sorry for the late reply.
It would be better if we could release aarch64 binary package.
Thanks for the suggestion and PR.
