### ISSUE TITLE
[discussion] versioning rule

### ISSUE THREAD

**Issue by izziiyt** [rixwew/darts-clone-python#5]
Hi @rixwew I have a question.

Is this repo following semantic versioning schema (https://semver.org/lang/ja/) ?

I remembered all version changes we met is all minor, so I wondering what schema `dartsclone` follows.

I and @sorami is wondering which, `dartsclone ~= a.a.a` or `dartsclone >= a.a.a`, is better.
https://github.com/WorksApplications/SudachiPy/pull/111#issuecomment-564850433

**Comment by rixwew** [comment]
@izziiyt  I'm sorry for your inconvenience.
In the next release, I'll do version this package by following semantic versioning. 
Thank you for your suggestion.
